name: custom_linear_progress_indicator
description: "Provides a customizable linear progress indicator widget for Flutter applications, offering animation and visual customization options."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/custom_linear_progress_indicator.git"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:


